resolver: lts-12.26

extra-deps:
- esqueleto-2.7.0

docker:
  enable: false

image:
  container:
    name: errfrom/hn
    base: fpco/stack-build
    add:
      config: /app/config
      static: /app/static
    executables:
      - selective-shop
    entrypoints:
      - stack
